<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="$(BuildingBlocksPackageId)"/>
    <PackageReference Include="MessagePack"/>
    <PackageReference Include="MessagePackAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
